FROM golang:latest

RUN mkdir -p /go/src/github.com/pchain/ethermint
WORKDIR /go/src/github.com/pchain/ethermint

COPY Makefile /go/src/github.com/pchain/ethermint/
COPY glide.yaml /go/src/github.com/pchain/ethermint/
COPY glide.lock /go/src/github.com/pchain/ethermint/

RUN make get_vendor_deps

COPY . /go/src/github.com/pchain/ethermint
